### ISSUE TITLE
request: change default settings in the encoder

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo-Encoder#247]
I did some testing with default encoding settings and changing the defaults a little it saved me a huge amount of filesize and got an equal quality in video.

I changed the presets setting from ultrafast to veryfast. It takes a 10% longer but the file size almost was 50%.
Online i found : [link to a test with presets ](https://write.corbpie.com/ffmpeg-preset-comparison-x264-2019-encode-speed-and-file-size/)

I would request it to change the default settings to veryfast.

**Comment by akhilleusuggo** [comment]
It's something personal . Everybody uses the command lines that fits his needs .
I use totally different settings , I keep only the crucial flags `{$pathFileName}`& `{$destinationFile}`

**Comment by ronaldod** [comment]
It is personal, true. But it is always nice to have a good start and have not you test server getting filled with with huge files what maybe get people worried stop using this nice product. 

> I use totally different settings , I keep only the crucial flags {$pathFileName}& {$destinationFile}

That means you run on medium. And the other settings are all gone except for resolution i presume.

**Comment by akhilleusuggo** [comment]
@ronaldod I've said , that I have different parameters ( not that I don't have ) , complex to fit my needs . I use all this flags : 
`-preset` , `-profile` , `-level` , `-rc` , `-cq` , `-tune` , `-crf` ( instead of bitrate , just `minrate` and `maxrate` , `bufsize`) 

Depends of what type of content you're planing to host . If you're just gonna host content where quality doesn't mater , then any parameter is ok .
I also have a gpu server with different parameters ( nvidia and quicksync )

**Comment by ronaldod** [comment]
@akhilleusuggo Thanks for your information. And i see the request is accepted.
